/// \file
/// \addtogroup EffectPlayer
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from effect_player.djinni

#pragma once

#include <optional>
#include <string>
#include <utility>

namespace bnb { namespace interfaces {

struct process_image_params final {
    /** For internal use, not for clients. Stores path to JSON with face data, to mock frx results */
    std::optional<std::string> face_data_json_path;

    process_image_params(std::optional<std::string> face_data_json_path_)
    : face_data_json_path(std::move(face_data_json_path_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

