// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from types.djinni

#import "BNBPixelRect.h"
#import <Foundation/Foundation.h>


#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBAcneRegions : NSObject
- (nonnull instancetype)initWithRegions:(nonnull NSArray<BNBPixelRect *> *)regions
                         basisTransform:(nonnull NSArray<NSNumber *> *)basisTransform;
+ (nonnull instancetype)acneRegionsWithRegions:(nonnull NSArray<BNBPixelRect *> *)regions
                                basisTransform:(nonnull NSArray<NSNumber *> *)basisTransform;

@property (nonatomic, readonly, nonnull) NSArray<BNBPixelRect *> * regions;

/** (common -> rect) transformation */
@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * basisTransform;

@end
