// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from neuro_beauty.djinni

#import <Foundation/Foundation.h>


#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBAutoTuneOutput : NSObject
- (nonnull instancetype)initWithBrightness:(float)brightness
                                  contrast:(float)contrast;
+ (nonnull instancetype)autoTuneOutputWithBrightness:(float)brightness
                                            contrast:(float)contrast;

@property (nonatomic, readonly) float brightness;

@property (nonatomic, readonly) float contrast;

@end
