// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, BNBAttachmentStoreOp)
{
    /**
     * Save pixels, to be read later by sampler 
     * or loaded in the next frame
     */
    BNBAttachmentStoreOpSave,
    /** No need to store pixels after pass finish */
    BNBAttachmentStoreOpDiscard,
};
