// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import "BNBAttachmentLoadOp.h"
#import "BNBAttachmentStoreOp.h"
#import "BNBPixelFormatType.h"
#import "BNBVec4.h"
#import <Foundation/Foundation.h>


#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBAttachmentInfo : NSObject
- (nonnull instancetype)initWithLoadBehaviour:(BNBAttachmentLoadOp)loadBehaviour
                               storeBehaviour:(BNBAttachmentStoreOp)storeBehaviour
                                       format:(BNBPixelFormatType)format
                                   clearColor:(nonnull BNBVec4 *)clearColor
                              generateMipmaps:(BOOL)generateMipmaps;
+ (nonnull instancetype)attachmentInfoWithLoadBehaviour:(BNBAttachmentLoadOp)loadBehaviour
                                         storeBehaviour:(BNBAttachmentStoreOp)storeBehaviour
                                                 format:(BNBPixelFormatType)format
                                             clearColor:(nonnull BNBVec4 *)clearColor
                                        generateMipmaps:(BOOL)generateMipmaps;

@property (nonatomic, readonly) BNBAttachmentLoadOp loadBehaviour;

@property (nonatomic, readonly) BNBAttachmentStoreOp storeBehaviour;

@property (nonatomic, readonly) BNBPixelFormatType format;

@property (nonatomic, readonly, nonnull) BNBVec4 * clearColor;

@property (nonatomic, readonly) BOOL generateMipmaps;

@end
