// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from neuro_beauty.djinni

#import <Foundation/Foundation.h>

__attribute__((__visibility__("default"))) @interface BNBAutoTuneOutput : NSObject
- (nonnull instancetype)initWithBrightness:(float)brightness
                                  contrast:(float)contrast;
+ (nonnull instancetype)autoTuneOutputWithBrightness:(float)brightness
                                            contrast:(float)contrast;

@property (nonatomic, readonly) float brightness;

@property (nonatomic, readonly) float contrast;

@end
