// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, BNBBlendingMode)
{
    BNBBlendingModeOff,
    BNBBlendingModeAlpha,
    BNBBlendingModePremulAlpha,
    BNBBlendingModeAlphaRgba,
    BNBBlendingModeScreen,
    BNBBlendingModeAdd,
    BNBBlendingModeMultiply,
    BNBBlendingModeMin,
    BNBBlendingModeMax,
};
