// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>


/**class which is controller for beauty morphing update. Subclass of face_morphing. */

#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBBeautyMorphing : NSObject

/**
 *Sets face morphing weight.
 *@param value (float) morphing weight.
 */
- (void)setFaceWeight:(float)value;

/**@return morphing weight (float). */
- (float)getFaceWeight;

/**
 *Sets nose morphing weight.
 *@param value (float) morphing weight.
 */
- (void)setNoseWeight:(float)value;

/**@return morphing weight (float). */
- (float)getNoseWeight;

/**
 *Sets nose morphing weight.
 *@param value (float) morphing weight.
 */
- (void)setEyesWeight:(float)value;

/**@return morphing weight (float). */
- (float)getEyesWeight;

@end
