// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import "BNBComponentType.h"
#import <Foundation/Foundation.h>
@class BNBFaceMorphing;
@class BNBFaceTracker;
@class BNBHandTracker;
@class BNBMeshInstance;
@class BNBTransformation3d;


/**Base component class. */
__attribute__((__visibility__("default"))) @interface BNBComponent : NSObject

/**@return component type. Can be face_tracker, transformation, mesh_instance or face_morphing. */
- (BNBComponentType)getComponentType;

/**cast component to face tracker subclass instance. Will throw if derived class is not instance of face_tracker. */
- (nullable BNBFaceTracker *)asFaceTracker;

/**cast component to mesh_instance subclass instance. Will throw if derived class is not instance of mesh_instance. */
- (nullable BNBMeshInstance *)asMeshInstance;

/**cast component to face_morphing subclass instance. Will throw if derived class is not instance of face_morphing. */
- (nullable BNBFaceMorphing *)asFaceMorphing;

/**cast component to transformation_3d subclass instance. Will throw if derived class is not instance of transformation_3d. */
- (nullable BNBTransformation3d *)asTransformation;

/**cast component to hand_tracker subclass instance. Will throw if derived class is not instance of hand_tracker. */
- (nullable BNBHandTracker *)asHandTracker;

@end
