// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from effect_player.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, BNBColorStd)
{
    BNBColorStdBt601,
    BNBColorStdBt709,
};
