// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import "BNBCameraTextureFormat.h"
#import <Foundation/Foundation.h>
@class BNBImage;


/**
 *Special class, which represent web or phone camera image textures. Because of different platfroms can provide YUV,
 * or RGBA camera texture representations camera texture can be represented in Y, UV, RGBA formats, depends on
 * platfrom. Subclass of image
 */
__attribute__((__visibility__("default"))) @interface BNBCameraTexture : NSObject

/**@return camera texture format (camera_texture_format). Can be Y, UV, or RGBA. */
- (BNBCameraTextureFormat)getFormat;

/**
 *set camera texture format for current texture.
 *@param format (camera_texture_format). Can be Y, UV, or RGBA.
 */
- (void)setFormat:(BNBCameraTextureFormat)format;

/**@return upcast to base type */
- (nullable BNBImage *)asImage;

@end
