// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>
@class BNBImage;
@class BNBResource;


/**Class, which repesent cubemap texture interface. Subclass of image */
__attribute__((__visibility__("default"))) @interface BNBCubemap : NSObject

- (void)loadResource:(nullable BNBResource *)res;

/**
 *Load cubemap texture data from specified file name. For now only supported .ktx (cuemap) images.
 *@param file_name (string): absolute path for image file.
 */
- (void)load:(nonnull NSString *)filename;

/**@return upcast to base type */
- (nullable BNBImage *)asImage;

@end
