// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>


/** Class, which provide dual filter blur algorithm adjust interface. */
__attribute__((__visibility__("default"))) @interface BNBDualFilterBlur : NSObject

- (void)setRadius:(int32_t)radius;

@end
