// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from types.djinni

#import "BNBEyesCorneoscleraMask.h"
#import "BNBEyesIrisMask.h"
#import "BNBEyesPupilMask.h"
#import <Foundation/Foundation.h>

__attribute__((__visibility__("default"))) @interface BNBEyesMask : NSObject
- (nonnull instancetype)initWithIris:(nonnull BNBEyesIrisMask *)iris
                        corneosclera:(nonnull BNBEyesCorneoscleraMask *)corneosclera
                               pupil:(nonnull BNBEyesPupilMask *)pupil;
+ (nonnull instancetype)eyesMaskWithIris:(nonnull BNBEyesIrisMask *)iris
                            corneosclera:(nonnull BNBEyesCorneoscleraMask *)corneosclera
                                   pupil:(nonnull BNBEyesPupilMask *)pupil;

@property (nonatomic, readonly, nonnull) BNBEyesIrisMask * iris;

@property (nonatomic, readonly, nonnull) BNBEyesCorneoscleraMask * corneosclera;

@property (nonatomic, readonly, nonnull) BNBEyesPupilMask * pupil;

@end
