// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from effect_player.djinni

#import <Foundation/Foundation.h>
@class BNBEffectPlayerConfiguration;


/** Configuration for EffectPlayer */

#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBEffectPlayerConfiguration : NSObject

/**
 * @param fxWidth Width of effect rendering area
 * @param fxHeight Height of effect rendering area
 */
+ (nullable BNBEffectPlayerConfiguration *)create:(int32_t)fxWidth
                                         fxHeight:(int32_t)fxHeight;

/** Init audio device. */
- (void)setAudioEnabled:(BOOL)enabled;

@end
