// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>

__attribute__((__visibility__("default"))) @interface BNBEyesStatus : NSObject
- (nonnull instancetype)initWithIsLeftOpen:(BOOL)isLeftOpen
                               isRightOpen:(BOOL)isRightOpen;
+ (nonnull instancetype)eyesStatusWithIsLeftOpen:(BOOL)isLeftOpen
                                     isRightOpen:(BOOL)isRightOpen;

@property (nonatomic, readonly) BOOL isLeftOpen;

@property (nonatomic, readonly) BOOL isRightOpen;

@end
