// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from effect_player.djinni

#import "BNBEffectInfo.h"
#import "BNBSize.h"
#import "BNBSurfaceData.h"
#import <Foundation/Foundation.h>
@class BNBEffect;
@protocol BNBEffectActivatedListener;
@protocol BNBEffectEventListener;
@protocol BNBErrorListener;
@protocol BNBHintListener;



#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBEffectManager : NSObject

/**
 * Add callback to receive errors messages from Effect Player.
 * Thread-safe. May be called from any thread
 */
- (void)addErrorListener:(nullable id<BNBErrorListener>)errorListener;

/**
 * Remove callback to receive errors messages from Effect Player.
 * Thread-safe. May be called from any thread
 */
- (void)removeErrorListener:(nullable id<BNBErrorListener>)errorListener;

/**
 * Add callback to receive user-visible messages from effects.
 * You should display them on UI.
 * Thread-safe. May be called from any thread
 */
- (void)addHintListener:(nullable id<BNBHintListener>)hintListener;

/**
 * Remove callback to receive user-visible messages from effects.
 * Thread-safe. May be called from any thread
 */
- (void)removeHintListener:(nullable id<BNBHintListener>)hintListener;

/**
 * Add callback to receive events from effect.
 * Thread-safe. May be called from any thread
 */
- (void)addEffectEventListener:(nullable id<BNBEffectEventListener>)effectEventListener;

/**
 * Remove callback to receive events from effect.
 * Thread-safe. May be called from any thread
 */
- (void)removeEffectEventListener:(nullable id<BNBEffectEventListener>)effectEventListener;

/**
 * Add callback to receive notifications on effect change.
 * Thread-safe. May be called from any thread
 */
- (void)addEffectActivatedListener:(nullable id<BNBEffectActivatedListener>)effectActivatedListener;

/**
 * Remove callback to receive notifications on effect change.
 * Thread-safe. May be called from any thread
 */
- (void)removeEffectActivatedListener:(nullable id<BNBEffectActivatedListener>)effectActivatedListener;

/** Create empty effect. If working directory path is empty string then effect assumed as an in-memory effect. */
- (nullable BNBEffect *)createEffect:(nonnull NSString *)workDir;

/**
 * Set current effect.
 * Thread-safe. May be called from any thread
 */
- (void)setCurrentEffect:(nullable BNBEffect *)effect;

/**
 * load and activate effect sync
 * MUST be called from the render thread
 */
- (nullable BNBEffect *)load:(nonnull NSString *)url;

/**
 * load effect async, activate in the draw() call when it will be ready
 * Thread-safe. May be called from any thread
 */
- (nullable BNBEffect *)loadAsync:(nonnull NSString *)url;

/**
 * Get effect info. May be called before loading effect
 * "render type" and "recognizer features" fields won't be filled
 * Thread-safe. May be called from any thread
 */
+ (nonnull BNBEffectInfo *)getEffectInfo:(nonnull NSString *)url;

/**
 * Unload effect from cache. if no currently loading effect -
 * works the same way as load(""); launches empty effect loading.
 * MUST be called from the render thread
 */
- (void)unload:(nullable BNBEffect *)effect;

/**
 * Get active effect
 * Thread-safe. May be called from any thread
 */
- (nullable BNBEffect *)current;

/**
 * Update effect loading state
 * @param sync syncronize effect manager, block until effect loaded
 * MUST be called from the render thread
 */
- (void)update:(BOOL)sync;

/**
 * Get current effect size
 * Thread-safe. May be called from any thread
 */
- (nonnull BNBSize *)effectSize;

/**
 * Get current surface size
 * Thread-safe. May be called from any thread
 */
- (nonnull BNBSize *)surfaceSize;

/**
 * Set effect audio volume.
 * Thread-safe. May be called from any thread
 * @param volume A value in range `[0, 1]`, where `1` means maximum volume.
 */
- (void)setEffectVolume:(float)volume;

/**
 * Changes effect player render size, should be called on render thread.
 * MUST be called from the render thread
 */
- (void)setEffectSize:(int32_t)fxWidth
             fxHeight:(int32_t)fxHeight;

/** set different render surfaces. Can be treated as void* */
- (void)setRenderSurface:(nonnull BNBSurfaceData *)data;

/** disable surface presentation. Needed for offscreen rendering */
- (void)disableSurfacePresentation;

@end
