// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>


#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBEyesStatus : NSObject
- (nonnull instancetype)initWithIsLeftOpen:(BOOL)isLeftOpen
                               isRightOpen:(BOOL)isRightOpen;
+ (nonnull instancetype)eyesStatusWithIsLeftOpen:(BOOL)isLeftOpen
                                     isRightOpen:(BOOL)isRightOpen;

@property (nonatomic, readonly) BOOL isLeftOpen;

@property (nonatomic, readonly) BOOL isRightOpen;

@end
