// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from types.djinni

#import "BNBCameraPosition.h"
#import "BNBPixelRect.h"
#import <Foundation/Foundation.h>
@class BNBFaceData;



#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBFaceData : NSObject

+ (nullable BNBFaceData *)create;

- (nonnull NSArray<NSNumber *> *)getLandmarks;

- (void)setLandmarks:(nonnull NSArray<NSNumber *> *)lms;

- (nonnull NSArray<NSNumber *> *)getLatents;

- (void)setLatents:(nonnull NSArray<NSNumber *> *)lats;

- (nonnull NSArray<NSNumber *> *)getVertices;

- (void)setVertices:(nonnull NSArray<NSNumber *> *)verts;

- (nonnull BNBCameraPosition *)getCameraPosition;

- (void)setCameraPosition:(nonnull BNBCameraPosition *)cam;

- (BOOL)hasFace;

- (nonnull BNBPixelRect *)getFaceRect;

- (void)setFaceRect:(nonnull BNBPixelRect *)rect;

@end
