// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from types.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, BNBFaceDataSource)
{
    BNBFaceDataSourceArKit,
    BNBFaceDataSourceRnd,
};
