// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from recognizer.djinni

#import "BNBFrameData.h"
#import <Foundation/Foundation.h>


@protocol BNBFeature

/**must return unique id (e.g. a feature pointer or a true random number(most likely) satisfies this criteria) */
- (int64_t)id;

- (nonnull NSString *)name;

- (BOOL)requiresMainThread;

- (void)clean;

- (void)process:(nullable BNBFrameData *)frameData;

- (void)postprocess:(nullable BNBFrameData *)fd
           futureFd:(nullable BNBFrameData *)futureFd;

@end
