// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from spal.djinni

#import <Foundation/Foundation.h>
@class BNBHaptic;


__attribute__((__visibility__("default"))) @interface BNBHaptic : NSObject

+ (nullable BNBHaptic *)create;

- (BOOL)isIosApiAvailable;

- (BOOL)isAndroidApiAvailable;

/** Common API (always available) */
- (void)vibrate;

/** iOS API: Taptic Engine (iPhone 6S, 6S Plus, and above) */
- (void)peak;

- (void)pop;

- (void)canceled;

- (void)tryAgain;

- (void)failed;

/** iOS API: Haptic Feedback (iPhone 7, 7 Plus, and above) */
- (void)success;

- (void)warning;

- (void)error;

- (void)light;

- (void)medium;

- (void)heavy;

- (void)selection;

/** Android API */
- (void)vibrateWithParams:(int64_t)durationMs
                amplitude:(int32_t)amplitude;

@end
