// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import "BNBHandTrackerType.h"
#import <Foundation/Foundation.h>
@class BNBComponent;
@class BNBHand;
@class BNBHandTracker;


__attribute__((__visibility__("default"))) @interface BNBHandTracker : NSObject

/**
 *Fabric method for hand creating.
 *@return created (hand_tracker).
 */
+ (nullable BNBHandTracker *)create;

/**
 *Sets hand to hand tracker.
 *@param hand (hand): hand asset
 */
- (void)setHand:(nullable BNBHand *)hand;

/**@return hand (hand): hand asset */
- (nullable BNBHand *)getHand;

/**@return tracker type. Can be hand_skelet or ring */
- (BNBHandTrackerType)getType;

/**@return tracker type. Can be hand_skelet or ring */
- (void)setType:(BNBHandTrackerType)type;

/**@return upcast to base type */
- (nullable BNBComponent *)asComponent;

@end
