// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from license_utils.djinni

#import <Foundation/Foundation.h>
@class BNBLicenseManager;



#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBInformer : NSObject

/** Send event to Banuba Servers with custom key and value */
+ (void)sendEvent:(nullable BNBLicenseManager *)manager
              key:(nonnull NSString *)key
            value:(nonnull NSString *)value;

@end
