// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from utils.djinni

#import <Foundation/Foundation.h>


/**
 * Only android interface.
 * The interface required for the correct closing of java image,
 * after pointers of the image planes have been freed on the cpp side.
 */

#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBImageReleaser : NSObject

/**
 * Increments the reference count by 1 for an interface pointer to a object.
 * MUST be called before release().
 */
- (void)addRef;

/**
 * Increments the reference count by number for an interface pointer to a object.
 * @param number number of add ref.
 * MUST be called before release().
 */
- (void)addRefCount:(int32_t)number;

/**
 * Decrements the reference count for an interface on a COM object.
 * After the last ref is deleted, the java image will be closed(released).
 * MUST be called from the deleters of bnb::color_plane.
 */
- (void)release;

@end
