// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from effect_player.djinni

#import <Foundation/Foundation.h>


/** Callback for JS execution results. */
@protocol BNBJsCallback

/**
 * This method will be executed on the render thread. 
 * Try not to return as fast as possible.
 * param result String represenation of execution result.
 */
- (void)onResult:(nonnull NSString *)result;

@end
