// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from license_utils.djinni

#import "BNBLicenseStatus.h"
#import <Foundation/Foundation.h>
@class BNBLicenseManager;


/** This class incapsulates information about Client Token. */
__attribute__((__visibility__("default"))) @interface BNBLicenseManager : NSObject

/** Creates *new* `LicenceManager`. This metod won't change Banuba SDK internal state. */
+ (nullable BNBLicenseManager *)create:(nonnull NSString *)clientToken;

/**
 * Returns the instance used by Banuba SDK to check licence.
 * This istance was created by `UtilityManager.initialize`.
 */
+ (nullable BNBLicenseManager *)instance;

/** Checks if Client Token is expired. */
- (BNBLicenseStatus)isExpired;

/** Returns decoded content of Client Token */
- (nonnull NSString *)getJson;

@end
