// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from license_utils.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, BNBLicenseStatus)
{
    BNBLicenseStatusValid,
    BNBLicenseStatusRevoked,
    BNBLicenseStatusTimeBombed,
};
