// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>


/**Base class, represents media files handling. */

#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBMedia : NSObject

/**
 *set playback start position.
 *@param position (float): playback start position (seconds)
 */
- (void)setStartPosition:(float)position;

/**
 *set playback end position.
 *@param position (float): playback end position (seconds)
 */
- (void)setEndPosition:(float)position;

/**
 *set playback looping.
 *@param looped (bool): loop playback flag
 */
- (void)setLooped:(BOOL)looped;

/**@return loop playback flag (bool) */
- (BOOL)isLooped;

/**@return playback start position (float) */
- (float)getStartPosition;

/**@return playback end position (float) */
- (float)getEndPosition;

/**@return playback active flag. */
- (BOOL)isPlaying;

/**starts video playback */
- (void)play;

/**pause video playback */
- (void)pause;

/**stop video playback */
- (void)stop;

/**resume paused video playback */
- (void)resume;

@end
