// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>

__attribute__((__visibility__("default"))) @interface BNBMat2x4 : NSObject
- (nonnull instancetype)initWithM11:(float)m11
                                m12:(float)m12
                                m13:(float)m13
                                m14:(float)m14
                                m21:(float)m21
                                m22:(float)m22
                                m23:(float)m23
                                m24:(float)m24;
+ (nonnull instancetype)mat2x4WithM11:(float)m11
                                  m12:(float)m12
                                  m13:(float)m13
                                  m14:(float)m14
                                  m21:(float)m21
                                  m22:(float)m22
                                  m23:(float)m23
                                  m24:(float)m24;

@property (nonatomic, readonly) float m11;

@property (nonatomic, readonly) float m12;

@property (nonatomic, readonly) float m13;

@property (nonatomic, readonly) float m14;

@property (nonatomic, readonly) float m21;

@property (nonatomic, readonly) float m22;

@property (nonatomic, readonly) float m23;

@property (nonatomic, readonly) float m24;

@end
