// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>


/**Class, represents 3D mesh interface */

#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBMesh : NSObject

/**@return mesh name (string) */
- (nonnull NSString *)getName;

/**@return sub geometries names list (list<string>) */
- (nonnull NSArray<NSString *> *)getSubGeometries;

/**@return animations names list (list<string>) */
- (nonnull NSArray<NSString *> *)getAnimations;

@end
