// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from neuro_beauty.djinni

#import "BNBAutoTuneOutput.h"
#import "BNBFrameData.h"
#import "BNBNeuroBeautyInput.h"
#import "BNBNeuroBeautyOutput.h"
#import "BanubaEffectPlayer/BNBFullImageData.h"
#import <Foundation/Foundation.h>
@class BNBNeuroBeauty;



#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBNeuroBeauty : NSObject

+ (nullable BNBNeuroBeauty *)create;

- (nullable BNBNeuroBeautyOutput *)applyTextures:(nullable BNBFrameData *)extFd
                                    beautyParams:(nonnull BNBNeuroBeautyInput *)beautyParams;

- (void)runPerfTest;

- (nonnull BNBAutoTuneOutput *)executeAutoTune:(nonnull BNBFullImageData *)sourceImage;

@end
