// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from neuro_beauty.djinni

#import <Foundation/Foundation.h>

/** Tuple with neuro_beauty output. */
__attribute__((__visibility__("default"))) @interface BNBNeuroBeautyOutput : NSObject
- (nonnull instancetype)initWithWidth:(int32_t)width
                               height:(int32_t)height
                             channels:(int32_t)channels
                                image:(nonnull NSData *)image;
+ (nonnull instancetype)neuroBeautyOutputWithWidth:(int32_t)width
                                            height:(int32_t)height
                                          channels:(int32_t)channels
                                             image:(nonnull NSData *)image;

@property (nonatomic, readonly) int32_t width;

@property (nonatomic, readonly) int32_t height;

@property (nonatomic, readonly) int32_t channels;

@property (nonatomic, readonly, nonnull) NSData * image;

@end
