// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from effect_player.djinni

#import <Foundation/Foundation.h>

/** Describes strategies for features which depend on Neural Networks */
typedef NS_ENUM(NSInteger, BNBNnMode)
{
    /** Means automatically decision, based on device performance and compatibility of NN's player with current platform */
    BNBNnModeAutomatically,
    /** Means enable NN's when current platform compatible with NN's player */
    BNBNnModeEnable,
    /** Means disable in any case */
    BNBNnModeDisable,
};
