// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>

/** All available images processing algorithms. */
typedef NS_ENUM(NSInteger, BNBProceduralAlgorithmType)
{
    /**
     * Doesn't requires any src image on input.
     * Result: RGBA camera image with correct device-relative orientation.
     */
    BNBProceduralAlgorithmTypeCameraComposer,
    /**
     * Doesn't requires any src image on input.
     * Result: RGBA processed image using neural networks beautification.
     */
    BNBProceduralAlgorithmTypeNeuroBeautification,
};
