// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import "BNBMat2x4.h"
#import "BNBMat3x4.h"
#import "BNBMat4x4.h"
#import "BNBVec3.h"
#import "BNBVec4.h"
#import <Foundation/Foundation.h>
@class BNBParameter;


/**Class, represent shader parameter. */

#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBParameter : NSObject

/**
 *Fabric method for parameter creating.
 *@param name (string): parameter name.
 *@return created parameter (parameter)
 */
+ (nullable BNBParameter *)create:(nonnull NSString *)name;

/**@return parameter name (string) */
- (nonnull NSString *)getName;

/**
 *set parameter integer value.
 *@param value (int)
 */
- (void)setInteger:(int32_t)value;

/**return parameter int value. Throw is type is not equal type, which was added earlier. */
- (int32_t)getInteger;

/**
 *set parameter real value.
 *@param value (float)
 */
- (void)setReal:(float)value;

/**return parameter f32 value. Throw is type is not equal type, which was added earlier. */
- (float)getReal;

/**
 *set parameter string value.
 *@param value (string)
 */
- (void)setString:(nonnull NSString *)value;

/**return parameter string value. Throw is type is not equal type, which was added earlier. */
- (nonnull NSString *)getString;

/**
 *set parameter vec3 value.
 *@param value (vec3)
 */
- (void)setVector3:(nonnull BNBVec3 *)value;

/**return parameter vec3 value. Throw is type is not equal type, which was added earlier. */
- (nonnull BNBVec3 *)getVector3;

/**
 *set parameter vec4 value.
 *@param value (vec4)
 */
- (void)setVector4:(nonnull BNBVec4 *)value;

/**return parameter vec4 value. Throw is type is not equal type, which was added earlier. */
- (nonnull BNBVec4 *)getVector4;

/**
 *set parameter mat2x4 value.
 *@param value (mat2x4)
 */
- (void)setMat2x4:(nonnull BNBMat2x4 *)value;

/**return parameter mat2x4 value. Throw is type is not equal type, which was added earlier. */
- (nonnull BNBMat2x4 *)getMat2x4;

/**
 *set parameter mat3x4 value.
 *@param value (mat3x4)
 */
- (void)setMat3x4:(nonnull BNBMat3x4 *)value;

/**return parameter mat3x4 value. Throw is type is not equal type, which was added earlier. */
- (nonnull BNBMat3x4 *)getMat3x4;

/**
 *set parameter mat4x4 value.
 *@param value (mat4x4)
 */
- (void)setMat4x4:(nonnull BNBMat4x4 *)value;

/**return parameter mat4x4 value. Throw is type is not equal type, which was added earlier. */
- (nonnull BNBMat4x4 *)getMat4x4;

@end
