// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from effect_player.djinni

#import <Foundation/Foundation.h>
@class BNBProcessorConfiguration;



#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBProcessorConfiguration : NSObject

/** Create with default params */
+ (nullable BNBProcessorConfiguration *)create;

/**
 * Use future frame filter, improves anti-jitter, adds processed frame inconsistency
 * Default: true
 */
- (void)setUseFutureFilter:(BOOL)value;

/**
 * Use offline recognizer mode for processing
 * Default: false
 */
- (void)setUseOfflineMode:(BOOL)value;

@end
