// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from types.djinni

#import "BNBPixelFormat.h"
#import <Foundation/Foundation.h>

__attribute__((__visibility__("default"))) @interface BNBPixelBuffer : NSObject
- (nonnull instancetype)initWithData:(nonnull NSData *)data
                              format:(BNBPixelFormat)format
                               width:(int32_t)width
                              heigth:(int32_t)heigth;
+ (nonnull instancetype)pixelBufferWithData:(nonnull NSData *)data
                                     format:(BNBPixelFormat)format
                                      width:(int32_t)width
                                     heigth:(int32_t)heigth;

@property (nonatomic, readonly, nonnull) NSData * data;

@property (nonatomic, readonly) BNBPixelFormat format;

@property (nonatomic, readonly) int32_t width;

@property (nonatomic, readonly) int32_t heigth;

@end
