// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>

/** All available images processing algorithms. */
typedef NS_ENUM(NSInteger, BNBProceduralAlgorithmType)
{
    /**
     * Doesn't requires any src image on input.
     * Result: RGBA camera image with correct device-relative orientation.
     */
    BNBProceduralAlgorithmTypeCameraComposer,
    /**
     * Requires src image on input. Currently image must be full screen resolution attachment, otherwise blur will be applied with incorrect kernel.
     * Only OpenGL(es) 3+ feature. (i.e. currently will not work in Safari).
     * Result: blurred image.
     */
    BNBProceduralAlgorithmTypeDualFilterBlur,
    /**
     * Doesn't requires any src image on input.
     * Result: RGBA processed image using neural networks beautification.
     */
    BNBProceduralAlgorithmTypeNeuroBeautification,
};
