// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from effect_player.djinni

#import <Foundation/Foundation.h>
@class BNBProcessorConfiguration;



#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBProcessorConfiguration : NSObject

/** Create with default params */
+ (nullable BNBProcessorConfiguration *)create;

/**
 * Use future frame to filter prediction, improves anti-jitter, adds processed frame inconsistency
 * Example: push frame 1 - pop frame 1, push frame 2 - pop frame 1, push frame 3 - pop frame 2, ...
 * Cannot be used together with other configurations
 * Default: true
 */
- (void)setUseFutureFilter:(BOOL)value;

/**
 * Use future frame to interpolate prediction, improves performance, adds processed frame inconsistency
 * Example: push frame 1 - pop frame 1, push frame 2 - pop frame 1, push frame 3 - pop frame 2, ...
 * Cannot be used together with other configurations
 * Default: false
 */
- (void)setUseFutureInterpolate:(BOOL)value;

/**
 * Use offline NN's for processing, improces accuracy in exchange to performance
 * Cannot be used together with other configurations
 * Default: false
 */
- (void)setUseOfflineMode:(BOOL)value;

@end
