// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from effect_player.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, BNBProcessorStatus)
{
    /** Processed frame data */
    BNBProcessorStatusOk,
    /** Processor output buffer is empty */
    BNBProcessorStatusEmpty,
    /** Processing is skipped */
    BNBProcessorStatusSkip,
    /** Error happen, check log */
    BNBProcessorStatusError,
};
