// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from effect_player.djinni

#import "BNBFrameData.h"
#import "BNBProcessorStatus.h"
#import <Foundation/Foundation.h>


#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBProcessorResult : NSObject
- (nonnull instancetype)initWithStatus:(BNBProcessorStatus)status
                             frameData:(nullable BNBFrameData *)frameData;
+ (nonnull instancetype)processorResultWithStatus:(BNBProcessorStatus)status
                                        frameData:(nullable BNBFrameData *)frameData;

@property (nonatomic, readonly) BNBProcessorStatus status;

@property (nonatomic, readonly, nullable) BNBFrameData * frameData;

@end
