// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from effect_player.djinni

#import <Foundation/Foundation.h>

/** Data for creating surface */
__attribute__((__visibility__("default"))) @interface BNBSurfaceData : NSObject
- (nonnull instancetype)initWithGpuDevicePtr:(int64_t)gpuDevicePtr
                             commandQueuePtr:(int64_t)commandQueuePtr
                                  surfacePtr:(int64_t)surfacePtr;
+ (nonnull instancetype)surfaceDataWithGpuDevicePtr:(int64_t)gpuDevicePtr
                                    commandQueuePtr:(int64_t)commandQueuePtr
                                         surfacePtr:(int64_t)surfacePtr;

/** Pointer to device gpu */
@property (nonatomic, readonly) int64_t gpuDevicePtr;

/** Pointer to gpu command queue */
@property (nonatomic, readonly) int64_t commandQueuePtr;

/** Pointer to render layer */
@property (nonatomic, readonly) int64_t surfacePtr;

@end
