// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>


#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBShaderSource : NSObject
- (nonnull instancetype)initWithVs:(nonnull NSString *)vs
                                fs:(nonnull NSString *)fs;
+ (nonnull instancetype)shaderSourceWithVs:(nonnull NSString *)vs
                                        fs:(nonnull NSString *)fs;

@property (nonatomic, readonly, nonnull) NSString * vs;

@property (nonatomic, readonly, nonnull) NSString * fs;

@end
