// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from visual_clip.djinni

#import <Foundation/Foundation.h>


@protocol BNBVisualClipListener

- (BOOL)shouldContinueProcessing:(int32_t)completedFramesCount
                totalFramesCount:(int32_t)totalFramesCount;

@end
