// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>


/** Interface to receive loading result from `video`. */
@protocol BNBVideoLoadingResultListener

- (void)onLoadingFinished:(BOOL)success;

@end
