// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import "BNBTextureFilteringMode.h"
#import <Foundation/Foundation.h>
@class BNBImage;
@class BNBMedia;
@protocol BNBVideoLoadingResultListener;


/**Class, represents video texture interface. Subclass of image, also subclass of media. */

#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBVideo : NSObject

/**@return current loaded video file (string). */
- (nonnull NSString *)getCurrentVideo;

/**@return current loaded video pixels width (int). */
- (int32_t)getWidth;

/**@return current loaded video pixels height (int). */
- (int32_t)getHeight;

/**
 *Load video file for decoding.
 *@param file_name (string): absolute path for video file.
 */
- (void)load:(nonnull NSString *)videoPath
onLoadingFinished:(nullable id<BNBVideoLoadingResultListener>)onLoadingFinished;

/**
 *Load video file for decoding by file descriptor.
 *@param fd (i32): file descriptor, should be closed on the caller side.
 */
- (void)loadByFd:(int32_t)fd
onLoadingFinished:(nullable id<BNBVideoLoadingResultListener>)onLoadingFinished;

/**cast video to media parent class (media). */
- (nullable BNBMedia *)asMedia;

/**@return upcast to image type */
- (nullable BNBImage *)asImage;

/** Video own rotation angle */
- (float)getRotationAngle;

/**
 *set gpu video texture filtering mode
 *param mode (texture_filtering_mode)
 */
- (void)setFilteringMode:(BNBTextureFilteringMode)value;

/**@return filtering mode (texture_filtering_mode) */
- (BNBTextureFilteringMode)getFilteringMode;

@end
