/// \file
/// \addtogroup EffectPlayer
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#pragma once

#include "bnb/types/interfaces/pixel_rect.hpp"
#include <optional>
#include <utility>
#include <vector>

namespace bnb { namespace interfaces {

struct process_image_params final {
    /** Set this param to force running of acne processing feature */
    bool acne_processing;
    /** User-defined acne areas to mask, rectangles are in input image coordinate space */
    std::optional<std::vector<::bnb::interfaces::pixel_rect>> acne_user_areas;

    process_image_params(bool acne_processing_,
                         std::optional<std::vector<::bnb::interfaces::pixel_rect>> acne_user_areas_)
    : acne_processing(std::move(acne_processing_))
    , acne_user_areas(std::move(acne_user_areas_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

