// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, BNBAttachmentLoadOp)
{
    /**
     * Don't care about attachment content at the pass 
     * start (pass will overwrite all pixels)
     */
    BNBAttachmentLoadOpDontCare,
    /** Clear to `clear_color` at pass start */
    BNBAttachmentLoadOpClear,
    /** load pixels from the previous frame */
    BNBAttachmentLoadOpLoad,
};
