// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from renderer_common.djinni

#import "BanubaEffectPlayer/BNBFullImageData.h"
#import <Foundation/Foundation.h>


#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBBnbMorphResult : NSObject
- (nonnull instancetype)initWithImg:(nonnull BNBFullImageData *)img
                          landmarks:(nonnull NSArray<NSNumber *> *)landmarks;
+ (nonnull instancetype)bnbMorphResultWithImg:(nonnull BNBFullImageData *)img
                                    landmarks:(nonnull NSArray<NSNumber *> *)landmarks;

@property (nonatomic, readonly, nonnull) BNBFullImageData * img;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * landmarks;

@end
