// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from types.djinni

#import <Foundation/Foundation.h>


#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBCameraPosition : NSObject
- (nonnull instancetype)initWithModelViewM:(nonnull NSArray<NSNumber *> *)modelViewM
                               projectionM:(nonnull NSArray<NSNumber *> *)projectionM;
+ (nonnull instancetype)cameraPositionWithModelViewM:(nonnull NSArray<NSNumber *> *)modelViewM
                                         projectionM:(nonnull NSArray<NSNumber *> *)projectionM;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * modelViewM;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * projectionM;

@end
