// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import "BNBCameraParameters.h"
#import <Foundation/Foundation.h>


__attribute__((__visibility__("default"))) @interface BNBCamera : NSObject

- (void)setParameters:(nonnull BNBCameraParameters *)parameters;

- (nonnull BNBCameraParameters *)getParameters;

@end
