// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>
@class BNBImage;
@class BNBVideo;


/** Class, which provide camera composer algorithms adjust interface. */

#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBCameraComposer : NSObject

/**
 * Pass empty path to reset background image.
 * Supported extensions: jpg, jpeg, png, mp4, gif
 * play and loop args only for video
 */
- (void)setBackgroundImage:(nonnull NSString *)path
                      play:(BOOL)play
                      loop:(BOOL)loop;

- (void)setBackgroundImageByFd:(int32_t)fd;

- (void)setBackgroundVideoByFd:(int32_t)fd
                          play:(BOOL)play
                          loop:(BOOL)loop;

- (nullable BNBImage *)getBackgroundImage;

- (nullable BNBVideo *)getBackgroundVideo;

- (void)enableBlur:(BOOL)enable;

- (void)setBlurRadius:(int32_t)radius;

- (void)setBgTransparencyFactor:(float)factor;

- (void)setRotation:(float)degrees;

- (void)setScale:(float)x
               y:(float)y;

- (void)setContentMode:(int32_t)mode;

- (void)setBackgroundColor:(float)r
                         g:(float)g
                         b:(float)b
                         a:(float)a;

@end
