// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import "BNBCameraParameters.h"
#import <Foundation/Foundation.h>



#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBCamera : NSObject

- (void)setParameters:(nonnull BNBCameraParameters *)parameters;

- (nonnull BNBCameraParameters *)getParameters;

@end
