// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from types.djinni

#import <Foundation/Foundation.h>

/** Results from depth camera */

#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBDepthMap : NSObject
- (nonnull instancetype)initWithDepthData:(nonnull NSData *)depthData
                            depthMapWidth:(int32_t)depthMapWidth
                           depthMapHeight:(int32_t)depthMapHeight;
+ (nonnull instancetype)depthMapWithDepthData:(nonnull NSData *)depthData
                                depthMapWidth:(int32_t)depthMapWidth
                               depthMapHeight:(int32_t)depthMapHeight;

@property (nonatomic, readonly, nonnull) NSData * depthData;

@property (nonatomic, readonly) int32_t depthMapWidth;

@property (nonatomic, readonly) int32_t depthMapHeight;

@end
