// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from utils.djinni

#import <Foundation/Foundation.h>
@class BNBEglContext;


__attribute__((__visibility__("default"))) @interface BNBEglContext : NSObject

+ (nullable BNBEglContext *)create:(int32_t)width
                            height:(int32_t)height;

- (BOOL)check;

- (void)activate;

- (void)deactivate;

@end
