// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from types.djinni

#import <Foundation/Foundation.h>


#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBEyesState : NSObject
- (nonnull instancetype)initWithIsOpenLeft:(BOOL)isOpenLeft
                               isOpenRight:(BOOL)isOpenRight;
+ (nonnull instancetype)eyesStateWithIsOpenLeft:(BOOL)isOpenLeft
                                    isOpenRight:(BOOL)isOpenRight;

@property (nonatomic, readonly) BOOL isOpenLeft;

@property (nonatomic, readonly) BOOL isOpenRight;

@end
