// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from types.djinni

#import "BNBTransformedMaskByte.h"
#import <Foundation/Foundation.h>


#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBEyesCorneoscleraMask : NSObject
- (nonnull instancetype)initWithLeft:(nonnull BNBTransformedMaskByte *)left
                               right:(nonnull BNBTransformedMaskByte *)right;
+ (nonnull instancetype)eyesCorneoscleraMaskWithLeft:(nonnull BNBTransformedMaskByte *)left
                                               right:(nonnull BNBTransformedMaskByte *)right;

@property (nonatomic, readonly, nonnull) BNBTransformedMaskByte * left;

@property (nonatomic, readonly, nonnull) BNBTransformedMaskByte * right;

@end
