// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from types.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, BNBFeatureId)
{
    BNBFeatureIdFrx,
    BNBFeatureIdPulse,
    BNBFeatureIdActionUnits,
    BNBFeatureIdBackground,
    BNBFeatureIdHair,
    BNBFeatureIdEyes,
    BNBFeatureIdBrows,
    BNBFeatureIdSkin,
    BNBFeatureIdFace,
    BNBFeatureIdLips,
    BNBFeatureIdLipsShine,
    BNBFeatureIdOcclussion,
    BNBFeatureIdGlasses,
    BNBFeatureIdAcne,
    BNBFeatureIdHandSkelet,
    BNBFeatureIdEyeBags,
    BNBFeatureIdFaceAcne,
    BNBFeatureIdRuler,
    BNBFeatureIdHairStrand,
    BNBFeatureIdRing,
    BNBFeatureIdNeck,
    /** Body segmentation. I.e. bodies detection on the frame. */
    BNBFeatureIdBody,
    /** Nails segmentation and recoloring  */
    BNBFeatureIdNails,
    /** Neuro beauty preprocessing */
    BNBFeatureIdBeautyPreproc,
    /** Combined face acne and eyebags removal */
    BNBFeatureIdAcneEyebags,
    BNBFeatureIdHandGestures,
    BNBFeatureIdTexturedNails,
    /** Activates eyes corrector */
    BNBFeatureIdEyesCorrection,
    /** Activates lips corrector */
    BNBFeatureIdLipsCorrection,
    /** Activates face mesh corrector */
    BNBFeatureIdFaceMeshCorrection,
    /** Computes coefficient for light correction */
    BNBFeatureIdLightCorrection,
};
