// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>
@class BNBMesh;


/**Class, represents face resources */

#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBFace : NSObject

/**@return face name (string) */
- (nonnull NSString *)getName;

/**@return face index (int) */
- (int32_t)getIndex;

/**
 *sets face index for face. Face mesh and textures will be updated according their faces index. 
 *If index will be greater than max faces can be found face resources update will be ignored.
 *@param index (int): face index
 */
- (void)setIndex:(int32_t)index;

/**
 *sets face mesh. Must be only "$builtin$meshes/face.stream" mesh.
 *@param mesh (mesh): face mesh
 */
- (void)setFaceMesh:(nullable BNBMesh *)mesh;

/**@return face mesh (mesh) */
- (nullable BNBMesh *)getFaceMesh;

@end
