// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from types.djinni

#import <Foundation/Foundation.h>

/**
 * User configurable parameters for in-CPU calculations during `FrameData`
 * processing. Meaning of this parameters are defined by features itself. 
 * Passed in list to `FrameData.addFeatureParameters`. 
 */

#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBFeatureParameter : NSObject
- (nonnull instancetype)initWithX:(float)x
                                y:(float)y
                                z:(float)z
                                w:(float)w;
+ (nonnull instancetype)featureParameterWithX:(float)x
                                            y:(float)y
                                            z:(float)z
                                            w:(float)w;

@property (nonatomic, readonly) float x;

@property (nonatomic, readonly) float y;

@property (nonatomic, readonly) float z;

@property (nonatomic, readonly) float w;

@end
