// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from types.djinni

#import "BNBTransformableEvent.h"
#import <Foundation/Foundation.h>
@class BNBFaceData;
@class BNBFrxRecognitionResult;



#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBFrxRecognitionResult : NSObject

+ (nullable BNBFrxRecognitionResult *)create;

- (nonnull NSArray<BNBFaceData *> *)getFaces;

- (void)setFaces:(nonnull NSArray<BNBFaceData *> *)faces;

- (nonnull NSArray<NSNumber *> *)getTexCoords;

- (nonnull NSArray<NSNumber *> *)getTriangles;

- (nonnull BNBTransformableEvent *)getTransform;

- (void)setTransform:(nonnull BNBTransformableEvent *)t;

@end
