// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from types.djinni

#import "BNBAcneRegions.h"
#import "BNBActionUnitsData.h"
#import "BNBBrowsMask.h"
#import "BNBDepthMap.h"
#import "BNBExternalFaceData.h"
#import "BNBEyesMask.h"
#import "BNBEyesState.h"
#import "BNBFaceDataSource.h"
#import "BNBFeatureParameter.h"
#import "BNBLipsShineMask.h"
#import "BNBNeuroBeautyData.h"
#import "BNBTransformedMaskByte.h"
#import "BNBTransformedMaskGpu.h"
#import "BanubaEffectPlayer/BNBFullImageData.h"
#import <Foundation/Foundation.h>
@class BNBFrameData;
@class BNBFrxRecognitionResult;


/**
 * getters throw exceptions when data are not available
 * android NNs usually output gpu masks
 */

#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBFrameData : NSObject

/** Creates empty `FrameData`. Use `add*` function to fill it.  */
+ (nullable BNBFrameData *)create;

- (nonnull NSArray<NSNumber *> *)getFullImgTransform;

/** Get frx_recognition_result or null if not exists */
- (nullable BNBFrxRecognitionResult *)getFrxRecognitionResult;

- (void)setFrxRecognitionResult:(nullable BNBFrxRecognitionResult *)result;

- (nonnull BNBActionUnitsData *)getActionUnits;

- (nonnull BNBAcneRegions *)getAcneRegions;

- (nonnull BNBNeuroBeautyData *)getNeuroBeautyData;

- (BOOL)getIsSmile;

- (BOOL)getIsMouthOpen;

- (BOOL)getIsBrowsRaised;

- (BOOL)getIsBrowsShifted;

- (BOOL)getIsWearGlasses;

- (float)getRuler;

- (nonnull BNBEyesState *)getEyesState;

- (float)getLightCorrection;

- (nonnull BNBTransformedMaskByte *)getBackground;

- (nonnull BNBTransformedMaskGpu *)getBackgroundGpu;

- (nonnull BNBTransformedMaskByte *)getHair;

- (nonnull BNBTransformedMaskGpu *)getHairGpu;

- (nonnull BNBTransformedMaskByte *)getSkin;

- (nonnull BNBTransformedMaskGpu *)getSkinGpu;

- (nonnull BNBTransformedMaskByte *)getLips;

- (nonnull BNBTransformedMaskGpu *)getLipsGpu;

- (nonnull BNBTransformedMaskByte *)getOcclusion;

- (nonnull BNBTransformedMaskByte *)getBody;

- (nonnull BNBLipsShineMask *)getLipsShine;

- (nonnull BNBBrowsMask *)getBrows;

- (nonnull BNBEyesMask *)getEyes;

- (nonnull BNBTransformedMaskByte *)getFace;

- (nonnull BNBTransformedMaskByte *)getFaceSkin;

- (void)addFullImg:(nonnull BNBFullImageData *)img;

- (void)replaceFullImg:(nonnull BNBFullImageData *)img;

- (void)addBackground:(nonnull BNBTransformedMaskByte *)mask;

- (void)addExternalFaceData:(BNBFaceDataSource)source
                       data:(nonnull NSArray<BNBExternalFaceData *> *)data;

- (void)addDepthMap:(nonnull BNBDepthMap *)depthMap;

- (void)addFrameNumber:(int64_t)frameNumber;

- (void)addActionUnitsData:(nonnull BNBActionUnitsData *)actionUnits;

/**
 * Extra parameters during in-CPU feature calculations.
 * Reference feature documentation. 
 */
- (void)addFeatureParameters:(nonnull NSArray<BNBFeatureParameter *> *)params;

@end
