// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from types.djinni

#import "BNBTransformableEvent.h"
#import <Foundation/Foundation.h>
@class BNBFaceData;
@class BNBFrxRecognitionResult;


__attribute__((__visibility__("default"))) @interface BNBFrxRecognitionResult : NSObject

+ (nullable BNBFrxRecognitionResult *)create;

- (nonnull NSArray<BNBFaceData *> *)getFaces;

- (void)setFaces:(nonnull NSArray<BNBFaceData *> *)faces;

- (nonnull NSArray<NSNumber *> *)getTexCoords;

- (void)setTexCoords:(nonnull NSArray<NSNumber *> *)texCoords;

- (nonnull NSArray<NSNumber *> *)getTriangles;

- (void)setTriangles:(nonnull NSArray<NSNumber *> *)triangles;

- (nonnull BNBTransformableEvent *)getTransform;

- (void)setTransform:(nonnull BNBTransformableEvent *)t;

@end
