// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import "BNBMorphingType.h"
#import <Foundation/Foundation.h>
@class BNBBeautyMorphing;
@class BNBComponent;
@class BNBFaceMorphing;
@class BNBMorphing;


/**class which is the container for morphind and update it's resources. Subclass of component. */
__attribute__((__visibility__("default"))) @interface BNBFaceMorphing : NSObject

/**
 *Fabric method for face_morphing creating.
 *@return created (face_morphing).
 */
+ (nullable BNBFaceMorphing *)create:(BNBMorphingType)type;

/**
 *Sets morphing asset.
 *@param morph (morphing) morphing instance.
 */
- (void)setMorphing:(nullable BNBMorphing *)morph;

/**@return setted morphing (morphing). */
- (nullable BNBMorphing *)getMorphing;

/**Cast to beauty_morphing subclass. */
- (nullable BNBBeautyMorphing *)asBeautyMorphing;

/**@return visible(bool) visibility flag. */
- (BOOL)isVisible;

/**
 *Set face_morphing visibility flag. 
 *Will be overridden if entity with mesh_instance component is child of entity with face_tracker component. Subclass of component.
 *@param visible(bool) visibility flag.
 */
- (void)setVisible:(BOOL)visible;

/**
 *set morphing weight. Must be in range [0, 1]
 *@param weight (float)
 */
- (void)setWeight:(float)weight;

/**@return current morph weight (float) */
- (float)getWeight;

/**@return upcast to base type */
- (nullable BNBComponent *)asComponent;

@end
