// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from types.djinni

#import "BNBRotation.h"
#import <Foundation/Foundation.h>


#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBFullImageFormat : NSObject
- (nonnull instancetype)initWithWidth:(int32_t)width
                               height:(int32_t)height
                          orientation:(BNBRotation)orientation;
+ (nonnull instancetype)fullImageFormatWithWidth:(int32_t)width
                                          height:(int32_t)height
                                     orientation:(BNBRotation)orientation;

@property (nonatomic, readonly) int32_t width;

@property (nonatomic, readonly) int32_t height;

@property (nonatomic, readonly) BNBRotation orientation;

@end
