// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, BNBImageType)
{
    BNBImageTypeAttachment,
    BNBImageTypeCubemap,
    BNBImageTypeSegmentationMask,
    BNBImageTypeTexture,
    BNBImageTypeCameraTexture,
    BNBImageTypeVideo,
    BNBImageTypeWeightedLut,
    BNBImageTypeTextTexture,
    BNBImageTypeProceduralTexture,
};
