// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import "BNBImageType.h"
#import <Foundation/Foundation.h>
@class BNBAttachment;
@class BNBCameraTexture;
@class BNBCubemap;
@class BNBProceduralTexture;
@class BNBSegmentationMask;
@class BNBTextTexture;
@class BNBTexture;
@class BNBVideo;
@class BNBWeightedLut;


/**Base class, which represented basic image interface */
__attribute__((__visibility__("default"))) @interface BNBImage : NSObject

/**@return image name (string) */
- (nonnull NSString *)getName;

/**@return image type. type of image subclass (enum, can be attachment, cubemap, segmentation_mask, texture, camera_texture, video, weighted_lut) */
- (BNBImageType)getType;

/**cast to attachment subclass. May throw. */
- (nullable BNBAttachment *)asAttachment;

/**cast to cubemap subclass. May throw. */
- (nullable BNBCubemap *)asCubemap;

/**cast to segmentation_mask subclass. May throw. */
- (nullable BNBSegmentationMask *)asSegmentationMask;

/**cast to texture subclass. May throw. */
- (nullable BNBTexture *)asTexture;

/**cast to camera_texture subclass. May throw. */
- (nullable BNBCameraTexture *)asCameraTexture;

/**cast to video subclass. May throw. */
- (nullable BNBVideo *)asVideo;

/**cast to weighted_lut subclass. May throw. */
- (nullable BNBWeightedLut *)asWeightedLut;

/**cast to text_texture subclass. May throw. */
- (nullable BNBTextTexture *)asTextTexture;

- (nullable BNBProceduralTexture *)asProceduralTexture;

@end
