// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>
@class BNBLayer;


/**
 *A container for entities, which is needed for explicit grouping entities in order in which they will be sent to render.
 *All morph entities must lay on the same layer.
 */

#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBLayer : NSObject

/**
 *Fabric method for layer creating.
 *@return created layer (layer).
 */
+ (nullable BNBLayer *)create:(nonnull NSString *)name;

/**
 *set layer name
 *@param layer name (string)
 */
- (void)setName:(nonnull NSString *)name;

/**@return layer name (string) */
- (nonnull NSString *)getName;

/**
 *Set enable/disable layer flag. The disabled layer will not be rendered.
 *@param active (bool) activity flag.
 */
- (void)setActive:(BOOL)active;

/**@return activity flag (bool) */
- (BOOL)isActive;

/**
 *ability for enable/disable morphing in specified layer
 *@param enable (bool)
 */
- (void)enableMorphing:(BOOL)enable;

/**@return is morphing enable in the current layer */
- (BOOL)isMorphingEnabled;

@end
