// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import "BNBMorphingType.h"
#import <Foundation/Foundation.h>
@class BNBMesh;


/**Class, represents morphing resources */

#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBMorphing : NSObject

/**@return morphing type (morphing_type) */
- (BNBMorphingType)getType;

/**@return morphing name (string) */
- (nonnull NSString *)getName;

/**
 *sets morphing warp mesh. If morhping type is beauty must be only "$builtin$meshes/beauty" mesh.
 *@param mesh (mesh): morphing warp mesh
 */
- (void)setWarpMesh:(nullable BNBMesh *)mesh;

/**@return warp (mesh) */
- (nullable BNBMesh *)getWarpMesh;

@end
