// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from neuro_beauty.djinni

#import "BNBSelectedLips.h"
#import <Foundation/Foundation.h>

/** Tuple with apply_texture neuro_beauty input. */
@interface BNBNeuroBeautyInput : NSObject
- (nonnull instancetype)initWithLutPath:(nonnull NSString *)lutPath
                            lutOnlySkin:(BOOL)lutOnlySkin
                               tonePath:(nonnull NSString *)tonePath
                              blushPath:(nonnull NSString *)blushPath
                    blushAutoCorrection:(BOOL)blushAutoCorrection
                                eyePath:(nonnull NSString *)eyePath
                         applyScleraMod:(BOOL)applyScleraMod
                     applyEyeFiltration:(BOOL)applyEyeFiltration
                            eyelashPath:(nonnull NSString *)eyelashPath
                      applyLipsMorphing:(BOOL)applyLipsMorphing
                       lipsMorphingMode:(BNBSelectedLips)lipsMorphingMode
                       lipsMorphingCoef:(float)lipsMorphingCoef;
+ (nonnull instancetype)neuroBeautyInputWithLutPath:(nonnull NSString *)lutPath
                                        lutOnlySkin:(BOOL)lutOnlySkin
                                           tonePath:(nonnull NSString *)tonePath
                                          blushPath:(nonnull NSString *)blushPath
                                blushAutoCorrection:(BOOL)blushAutoCorrection
                                            eyePath:(nonnull NSString *)eyePath
                                     applyScleraMod:(BOOL)applyScleraMod
                                 applyEyeFiltration:(BOOL)applyEyeFiltration
                                        eyelashPath:(nonnull NSString *)eyelashPath
                                  applyLipsMorphing:(BOOL)applyLipsMorphing
                                   lipsMorphingMode:(BNBSelectedLips)lipsMorphingMode
                                   lipsMorphingCoef:(float)lipsMorphingCoef;

@property (nonatomic, readonly, nonnull) NSString * lutPath;

@property (nonatomic, readonly) BOOL lutOnlySkin;

@property (nonatomic, readonly, nonnull) NSString * tonePath;

@property (nonatomic, readonly, nonnull) NSString * blushPath;

@property (nonatomic, readonly) BOOL blushAutoCorrection;

@property (nonatomic, readonly, nonnull) NSString * eyePath;

@property (nonatomic, readonly) BOOL applyScleraMod;

@property (nonatomic, readonly) BOOL applyEyeFiltration;

@property (nonatomic, readonly, nonnull) NSString * eyelashPath;

@property (nonatomic, readonly) BOOL applyLipsMorphing;

@property (nonatomic, readonly) BNBSelectedLips lipsMorphingMode;

@property (nonatomic, readonly) float lipsMorphingCoef;

@end
