// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from neuro_beauty.djinni

#import <Foundation/Foundation.h>

/** Tuple with apply_texture neuro_beauty input. */
__attribute__((__visibility__("default"))) @interface BNBNeuroBeautyInput : NSObject
- (nonnull instancetype)initWithSkinSmoothStrength:(float)skinSmoothStrength
                                           lutPath:(nonnull NSString *)lutPath
                                       lutOnlySkin:(BOOL)lutOnlySkin
                                          tonePath:(nonnull NSString *)tonePath
                                      toneStrength:(float)toneStrength
                                         blushPath:(nonnull NSString *)blushPath
                               blushAutoCorrection:(BOOL)blushAutoCorrection
                                           eyePath:(nonnull NSString *)eyePath
                                       shadowsPath:(nonnull NSString *)shadowsPath
                                      shadowsAlpha:(float)shadowsAlpha
                                    applyScleraMod:(BOOL)applyScleraMod
                                applyEyeFiltration:(BOOL)applyEyeFiltration
                                       eyelashPath:(nonnull NSString *)eyelashPath
                                      lipsPainting:(BOOL)lipsPainting
                                        lipsColorR:(float)lipsColorR
                                        lipsColorG:(float)lipsColorG
                                        lipsColorB:(float)lipsColorB;
+ (nonnull instancetype)neuroBeautyInputWithSkinSmoothStrength:(float)skinSmoothStrength
                                                       lutPath:(nonnull NSString *)lutPath
                                                   lutOnlySkin:(BOOL)lutOnlySkin
                                                      tonePath:(nonnull NSString *)tonePath
                                                  toneStrength:(float)toneStrength
                                                     blushPath:(nonnull NSString *)blushPath
                                           blushAutoCorrection:(BOOL)blushAutoCorrection
                                                       eyePath:(nonnull NSString *)eyePath
                                                   shadowsPath:(nonnull NSString *)shadowsPath
                                                  shadowsAlpha:(float)shadowsAlpha
                                                applyScleraMod:(BOOL)applyScleraMod
                                            applyEyeFiltration:(BOOL)applyEyeFiltration
                                                   eyelashPath:(nonnull NSString *)eyelashPath
                                                  lipsPainting:(BOOL)lipsPainting
                                                    lipsColorR:(float)lipsColorR
                                                    lipsColorG:(float)lipsColorG
                                                    lipsColorB:(float)lipsColorB;

@property (nonatomic, readonly) float skinSmoothStrength;

@property (nonatomic, readonly, nonnull) NSString * lutPath;

@property (nonatomic, readonly) BOOL lutOnlySkin;

@property (nonatomic, readonly, nonnull) NSString * tonePath;

@property (nonatomic, readonly) float toneStrength;

@property (nonatomic, readonly, nonnull) NSString * blushPath;

@property (nonatomic, readonly) BOOL blushAutoCorrection;

@property (nonatomic, readonly, nonnull) NSString * eyePath;

@property (nonatomic, readonly, nonnull) NSString * shadowsPath;

@property (nonatomic, readonly) float shadowsAlpha;

@property (nonatomic, readonly) BOOL applyScleraMod;

@property (nonatomic, readonly) BOOL applyEyeFiltration;

@property (nonatomic, readonly, nonnull) NSString * eyelashPath;

@property (nonatomic, readonly) BOOL lipsPainting;

@property (nonatomic, readonly) float lipsColorR;

@property (nonatomic, readonly) float lipsColorG;

@property (nonatomic, readonly) float lipsColorB;

@end
