// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, BNBPixelFormatType)
{
    BNBPixelFormatTypeR8,
    BNBPixelFormatTypeRg8,
    BNBPixelFormatTypeRgb8,
    BNBPixelFormatTypeRgba8,
    BNBPixelFormatTypeBgra8,
    BNBPixelFormatTypeR16f,
    BNBPixelFormatTypeRg16f,
    BNBPixelFormatTypeRgba16f,
    BNBPixelFormatTypeR32f,
    BNBPixelFormatTypeRgba32f,
    BNBPixelFormatTypeRgb10a2,
    BNBPixelFormatTypeDepth16,
    BNBPixelFormatTypeDepth24,
    BNBPixelFormatTypeDepth32f,
};
