// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from effect_player.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, BNBProcessorType)
{
    /** Live feed processor */
    BNBProcessorTypeRealtime,
    /** Photo processor */
    BNBProcessorTypePhoto,
    /** Video stream processor */
    BNBProcessorTypeVideo,
};
