// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from types.djinni

#import <Foundation/Foundation.h>

__attribute__((__visibility__("default"))) @interface BNBPoint2d : NSObject
- (nonnull instancetype)initWithX:(float)x
                                y:(float)y;
+ (nonnull instancetype)point2dWithX:(float)x
                                   y:(float)y;

@property (nonatomic, readonly) float x;

@property (nonatomic, readonly) float y;

@end
