// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from effect_player.djinni

#import <Foundation/Foundation.h>


#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBProcessImageParams : NSObject
- (nonnull instancetype)initWithFaceDataJsonPath:(nullable NSString *)faceDataJsonPath;
+ (nonnull instancetype)processImageParamsWithFaceDataJsonPath:(nullable NSString *)faceDataJsonPath;

/** For internal use, not for clients. Stores path to JSON with face data, to mock frx results */
@property (nonatomic, readonly, nullable) NSString * faceDataJsonPath;

@end
