// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>


/** Class, which resource abstraction.  */
__attribute__((__visibility__("default"))) @interface BNBResource : NSObject

- (BOOL)loaded;

- (nonnull NSString *)path;

@end
