// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>


/** Information getters */

#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBRenderInfo : NSObject

/** Recognition engine version */
+ (int32_t)getFrxVersion;

/** Platfrom name: ios, android */
+ (nonnull NSString *)getPlatform;

/** Render engine versio. Currently the same as SDK version. E.g.: `1.2.1-g8970518da` */
+ (nonnull NSString *)getEngineVersion;

@end
