// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from renderer_common.djinni

#import "BNBBnbMorphResult.h"
#import "BanubaEffectPlayer/BNBFullImageData.h"
#import <Foundation/Foundation.h>



#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBRendererCommon : NSObject

/** return rgba image, srcImage can be rgb or rgba */
+ (nonnull BNBFullImageData *)morphMesh:(nonnull BNBFullImageData *)srcImage
                          originalVerts:(nonnull NSArray<NSNumber *> *)originalVerts
                           morphedVerts:(nonnull NSArray<NSNumber *> *)morphedVerts
                                indices:(nonnull NSArray<NSNumber *> *)indices
                                    mvp:(nonnull NSArray<NSNumber *> *)mvp;

/** return rgba image, srcImage can be rgb or rgba */
+ (nonnull BNBBnbMorphResult *)morphMeshLandmarks:(nonnull BNBFullImageData *)srcImage
                                     srcLandmarks:(nonnull NSArray<NSNumber *> *)srcLandmarks
                                    originalVerts:(nonnull NSArray<NSNumber *> *)originalVerts
                                     morphedVerts:(nonnull NSArray<NSNumber *> *)morphedVerts
                                          indices:(nonnull NSArray<NSNumber *> *)indices
                                              mvp:(nonnull NSArray<NSNumber *> *)mvp;

@end
