// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from types.djinni

#import <Foundation/Foundation.h>


#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBSize : NSObject
- (nonnull instancetype)initWithWidth:(int32_t)width
                               height:(int32_t)height;
+ (nonnull instancetype)sizeWithWidth:(int32_t)width
                               height:(int32_t)height;

@property (nonatomic, readonly) int32_t width;

@property (nonatomic, readonly) int32_t height;

@end
