// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import "BNBSegmentationMaskType.h"
#import <Foundation/Foundation.h>
@class BNBImage;


/**Class, which repesent neural networks segmentation mask texture interface. Subclass of image */
__attribute__((__visibility__("default"))) @interface BNBSegmentationMask : NSObject

/**@return segmentation mask type. Can be background, hair, skin, lips, l_eye, r_eye. */
- (BNBSegmentationMaskType)getMaskType;

/**
 *set segmentation mask activity flag
 *@param active (bool): segmentation mask activity flag
 */
- (void)setActive:(BOOL)active;

/**@return segmentation mask activity flag (bool). */
- (BOOL)isActive;

/**@return upcast to base type */
- (nullable BNBImage *)asImage;

@end
