// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, BNBSegmentationMaskType)
{
    BNBSegmentationMaskTypeBackground,
    BNBSegmentationMaskTypeHair,
    BNBSegmentationMaskTypeSkin,
    BNBSegmentationMaskTypeLips,
    BNBSegmentationMaskTypeLEye,
    BNBSegmentationMaskTypeREye,
    BNBSegmentationMaskTypeLEyePupil,
    BNBSegmentationMaskTypeREyePupil,
    BNBSegmentationMaskTypeLEyeCorneosclera,
    BNBSegmentationMaskTypeREyeCorneosclera,
    BNBSegmentationMaskTypeLipsShining,
    BNBSegmentationMaskTypeOcclusion,
    BNBSegmentationMaskTypeBody,
    BNBSegmentationMaskTypeHairStrand,
    BNBSegmentationMaskTypeNeck,
    BNBSegmentationMaskTypeNeckSmoothing,
    BNBSegmentationMaskTypeSkinSmoothing,
    BNBSegmentationMaskTypeLBrow,
    BNBSegmentationMaskTypeRBrow,
    BNBSegmentationMaskTypeNails,
    BNBSegmentationMaskTypeFace,
};
