// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from utils.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, BNBSeverityLevel)
{
    BNBSeverityLevelDebug,
    BNBSeverityLevelInfo,
    BNBSeverityLevelWarning,
    BNBSeverityLevelError,
};
