// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import "BNBBlendingMode.h"
#import <Foundation/Foundation.h>


#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBState : NSObject
- (nonnull instancetype)initWithBlending:(BNBBlendingMode)blending
                                  zWrite:(BOOL)zWrite
                                   zTest:(BOOL)zTest
                              colorWrite:(BOOL)colorWrite
                               backFaces:(BOOL)backFaces
                                coverage:(BOOL)coverage;
+ (nonnull instancetype)stateWithBlending:(BNBBlendingMode)blending
                                   zWrite:(BOOL)zWrite
                                    zTest:(BOOL)zTest
                               colorWrite:(BOOL)colorWrite
                                backFaces:(BOOL)backFaces
                                 coverage:(BOOL)coverage;

@property (nonatomic, readonly) BNBBlendingMode blending;

@property (nonatomic, readonly) BOOL zWrite;

@property (nonatomic, readonly) BOOL zTest;

@property (nonatomic, readonly) BOOL colorWrite;

@property (nonatomic, readonly) BOOL backFaces;

@property (nonatomic, readonly) BOOL coverage;

@end
