// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>

__attribute__((__visibility__("default"))) @interface BNBShaderSource : NSObject
- (nonnull instancetype)initWithVs:(nonnull NSString *)vs
                                fs:(nonnull NSString *)fs;
+ (nonnull instancetype)shaderSourceWithVs:(nonnull NSString *)vs
                                        fs:(nonnull NSString *)fs;

@property (nonatomic, readonly, nonnull) NSString * vs;

@property (nonatomic, readonly, nonnull) NSString * fs;

@end
