// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from types.djinni

#import <Foundation/Foundation.h>

/**
 * User touch object.
 * Coordinate system is normalized to (-1, 1) with center in (0, 0).
 */
__attribute__((__visibility__("default"))) @interface BNBTouch : NSObject
- (nonnull instancetype)initWithX:(float)x
                                y:(float)y
                               id:(int64_t)id;
+ (nonnull instancetype)touchWithX:(float)x
                                 y:(float)y
                                id:(int64_t)id;

@property (nonatomic, readonly) float x;

@property (nonatomic, readonly) float y;

@property (nonatomic, readonly) int64_t id;

@end
