// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>

__attribute__((__visibility__("default"))) @interface BNBVec4 : NSObject
- (nonnull instancetype)initWithX:(float)x
                                y:(float)y
                                z:(float)z
                                w:(float)w;
+ (nonnull instancetype)vec4WithX:(float)x
                                y:(float)y
                                z:(float)z
                                w:(float)w;

@property (nonatomic, readonly) float x;

@property (nonatomic, readonly) float y;

@property (nonatomic, readonly) float z;

@property (nonatomic, readonly) float w;

@end
