// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from visual_clip.djinni

#import <Foundation/Foundation.h>


#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBVisualClipVideo : NSObject
- (nonnull instancetype)initWithPath:(nonnull NSString *)path
                       startPosition:(float)startPosition
                            duration:(float)duration;
+ (nonnull instancetype)visualClipVideoWithPath:(nonnull NSString *)path
                                  startPosition:(float)startPosition
                                       duration:(float)duration;

/** absolute path to video */
@property (nonatomic, readonly, nonnull) NSString * path;

/** start position in seconds */
@property (nonatomic, readonly) float startPosition;

/** duration in seconds */
@property (nonatomic, readonly) float duration;

@end
