// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>


#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBVec4 : NSObject
- (nonnull instancetype)initWithX:(float)x
                                y:(float)y
                                z:(float)z
                                w:(float)w;
+ (nonnull instancetype)vec4WithX:(float)x
                                y:(float)y
                                z:(float)z
                                w:(float)w;

@property (nonatomic, readonly) float x;

@property (nonatomic, readonly) float y;

@property (nonatomic, readonly) float z;

@property (nonatomic, readonly) float w;

@end
