// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>
@class BNBImage;
@class BNBResource;


__attribute__((__visibility__("default"))) @interface BNBWeightedLut : NSObject

- (void)loadResource:(nullable BNBResource *)res;

- (void)setWeight:(float)value;

- (float)getWeight;

- (void)load:(nonnull NSString *)fileName;

/**@return upcast to base type */
- (nullable BNBImage *)asImage;

@end
