// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>
@class BNBImage;
@class BNBResource;



#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface BNBWeightedLut : NSObject

- (void)loadResource:(nullable BNBResource *)res;

- (void)setWeight:(float)value;

- (float)getWeight;

- (void)load:(nonnull NSString *)fileName;

/**@return upcast to base type */
- (nullable BNBImage *)asImage;

@end
